# Generated by Django 4.2.7 on 2025-11-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_encoding',
            field=models.TextField(blank=True, help_text='Base64 encoded face recognition data', null=True),
        ),
    ]
